browser:
  browserName: chrome
  headlessBrowser: false
  webElementTimeOut: 15
  appUrl: http://146.59.32.4/index.php
currentEnv: test
environments:
  test:
    envName: test
    discount: -20%
    discountValue: 20
    discountLabel: SAVE 20%
    basketTestItemToAdd: 5
    basketTestProductToModify: 0
    basketTestProductQuantity: 5
  integrate:
    envName: integrate
